version: '3.8'

services:
  cots-hardware:
    image: ghcr.io/morten1603/third-party/redis:7.2.4
    ports:
      - "6379:6379"

  simulation-publisher:
    build:
      context: ../..
      dockerfile: simulation/Dockerfile
    image: simulation-publisher:local
    environment:
      - COTS_HOST=cots-hardware
      - COTS_PORT=6379
    depends_on:
      - cots-hardware
