services:
  cots-hardware:
    image: ghcr.io/morten1603/third-party/redis:7.2.4
    ports:
      - "6379:6379"

  nats:
    image: nats:alpine  
    ports:
      - "4222:4222"
    environment:
      - NATS_SERVER_URL=nats://localhost:4222
    depends_on:
      - px4-simulation
      - mavlink-bridge
      - c2-api

  px4-simulation:
    image: px4io/px4-sitl:latest
    network_mode: "host"
 
  mavlink-bridge:
    image: mavlink-router/mavlink-router:latest
    network_mode: "host"
    
  c2-api:
    build:
      context: ../..
      dockerfile: c2/Dockerfile
    image: c2-api:local
    ports:
      - "8000:8000"
    environment:
      - COTS_HOST=cots-hardware
      - COTS_PORT=6379
    depends_on:
      - cots-hardware
      - px4-simulation
